# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpodctl < Formula
  desc "runpodctl is a CLI tool to manage your GPU pods on RunPod."
  homepage "https://github.com/runpod/runpodctl"
  version "2.7.1"

  on_macos do
    url "https://github.com/runpod/runpodctl/releases/download/v2.7.1/runpodctl-darwin-all.tar.gz"
    sha256 "099a66afce63e27f58c2d0fc8393a1180b03cb02d3722d136008a4220bf07457"

    define_method(:install) do
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runpod/runpodctl/releases/download/v2.7.1/runpodctl-linux-amd64.tar.gz"
      sha256 "e39f1b7f63bf16d572de0d2fb71cfeff1a4785cd1e164126b3a65f30ab121c28"
      define_method(:install) do
        bin.install "runpodctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runpod/runpodctl/releases/download/v2.7.1/runpodctl-linux-arm64.tar.gz"
      sha256 "dcb316698008a288fba729dc6f851b566ab20d4f81ecab31c6a1fbe8a550ad6e"
      define_method(:install) do
        bin.install "runpodctl"
      end
    end
  end
end
