# This file was generated by GoReleaser. DO NOT EDIT.
cask "runpodctl" do
  version "2.15.0"

  on_macos do
    sha256 "931d16683f381c7302eefe0c59dc2868c96a756519ef4d90dd0624191ff06e72"
    url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-darwin-all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "06d9976edc48d99938322a8180213576cf88ffd2c7f9696bf89e6192648bc676"
      url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "bfa109cbb3eb4eca761d7e28211f01c9cbe21b292af7a1f5387d733f5be2475b"
      url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-linux-arm64.tar.gz"
    end
  end

  name "runpodctl"
  desc "runpodctl is a CLI tool to manage your GPU pods on RunPod."
  homepage "https://github.com/runpod/runpodctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runpodctl"

  # No zap stanza required

end
