# This file was generated by GoReleaser. DO NOT EDIT.
cask "runpodctl" do
  name "runpodctl"
  desc "runpodctl is a CLI tool to manage your GPU pods on RunPod."
  homepage "https://github.com/runpod/runpodctl"
  version "2.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runpodctl"

  on_macos do
    url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-darwin-all.tar.gz"
    sha256 "77907dd410f839313202f06b6ded5fe34f9e9986bccf5dce8f724e785c023da8"
  end

  on_linux do
    on_intel do
      url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-linux-amd64.tar.gz"
      sha256 "596d69c4b0ba47bbad01bb7c60d25575fffb11e27d4559057f17e7652677632c"
    end
    on_arm do
      url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-linux-arm64.tar.gz"
      sha256 "7409e2d40204357bd9d7852846b0b4db11557e4c00807f7c1a52c76c8c9e4743"
    end
  end

  # No zap stanza required
end
