# This file was generated by GoReleaser. DO NOT EDIT.
cask "runpodctl" do
  version "2.8.0"

  on_macos do
    sha256 "0690f17d74fe72db86b473f9096a97b0720c101691b01de85f9fb4b1bb3fdab4"
    url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-darwin-all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "39a367f85754a5695a095af569ea19a3ca88490066d8bb1598e0e29f680aa187"
      url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "7b76f350932aa020b89fcf38f57e6693e79ac1a87774ec1324e591641bb9c31a"
      url "https://github.com/runpod/runpodctl/releases/download/v#{version}/runpodctl-linux-arm64.tar.gz"
    end
  end

  name "runpodctl"
  desc "runpodctl is a CLI tool to manage your GPU pods on RunPod."
  homepage "https://github.com/runpod/runpodctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runpodctl"

  # No zap stanza required

end
